graph TD
    P0[Phase 0<br>0-15 min] -->|0.1| Bld(Draw 2 peripheral blood cultures)
    P0 -->|0.2| CSF(Collect CSF STAT)
    P0 -->|0.3| BioFire(Send 1 mL CSF to BioFire ME panel)
    P0 -->|0.4| Dex(Give dexamethasone 10 mg IV push + Empiric Abx)
    style P0 fill:#ffdede