graph TD
    P2[Phase 2<br>1-3 h] -->|2.1| MRI(Head MRI + MR-venography)
    P2 -->|2.2| Lines(Invasive arterial line & q1 h neuro-obs)
    P2 -->|2.3| Labs(Baseline labs)
    P2 -->|2.4| HRV(5-min HRV-biofeedback session)
    style P2 fill:#fff5b5